version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: staging
    image: otto-app-staging
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
