version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: otto-staging
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start
